assets:
  compress:
    css: false
    js: false
  sources:
    - guides/iguides-common/js
    - guides/iguides-common/css
    - guides/iguide-circuit-breaker/js
    - guides/iguide-circuit-breaker/css
    - guides/iguide-microprofile-config-intro/js
    - guides/iguide-microprofile-config-intro/css
    - guides/iguide-bulkhead/js
    - guides/iguide-bulkhead/css
    - guides/iguide-retry-timeout/js
    - guides/iguide-retry-timeout/css

minify_html: false

exclude:
  - feature
  - docs/templates