language: ruby
rvm:
- 2.4.1

before_install:
  - sudo apt-get install python3-bs4 -y

script: >
  if [ $TRAVIS_BRANCH = "master" ]; then
    cp robots.txt src/main/content/robots.txt
    JEKYLL_ENV=production ./scripts/build_jekyll_maven.sh
  else
    ./scripts/build_jekyll_maven.sh
  fi

# branch whitelist
branches:
  only:
    - master
    - development
    - multiPane
    - multiPane-stable

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  - provider: script
    skip_cleanup: true
    on:
      branch: master
    script: env ROUTE=qa-guides.mybluemix.net ./.travis/cf-push.sh
  - provider: script
    skip_cleanup: true
    on:
      branch: development
    script: env ROUTE=qa-guides-dev.mybluemix.net ./.travis/cf-push.sh
  - provider: script
    skip_cleanup: true
    on:
      branch: multiPane
    script: env ROUTE=qa-guides-multipane.mybluemix.net ./.travis/cf-push.sh
  - provider: script
    skip_cleanup: true
    on:
      branch: multiPane-stable
    script: env ROUTE=user-testing.mybluemix.net ./.travis/cf-push.sh
  - provider: script
    skip_cleanup: true
    on:
      branch: hotspots
    script: env ROUTE=hotspots.mybluemix.net ./.travis/cf-push.sh