language: ruby
rvm:
- 2.4.1

before_script:
 - chmod +x ./scripts/build_jekyll_maven.sh # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/build_jekyll_maven.sh

# branch whitelist
branches:
  only:
    - development

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $BLUEMIX_USER
  password: $BLUEMIX_PASSWORD
  organization: $BLUEMIX_ORGANIZATION
  space: $BLUEMIX_SPACE
  on:
    branch: development
