language: ruby
rvm:
- 2.4.1

before_script:
- chmod +x ./scripts/build_jekyll_maven.sh # or do this locally and commit


# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: ./scripts/build_jekyll_maven.sh

# branch whitelist
branches:
  only:
    - development

sudo: false # route your build to the container-based infrastructure for a faster build

before_deploy:
- chmod +x ./scripts/cf-blue-green.sh

deploy:
  provider: script
  script: ./scripts/cf-blue-green.sh
  skip_cleanup: true
  on:
    branch: development
