site:
  title: Open Liberty Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://antora.mybluemix.net/docs
  start_page: general::logging.adoc
content:
  sources:
  - url: https://github.com/OpenLiberty/docs.git
    branches: antora
    start_path: ref/general
  - url: https://github.com/OpenLiberty/docs.git
    branches: antora
    start_path: ref/config
  - url: https://github.com/OpenLiberty/docs.git
    branches: antora
    start_path: ref/feature
  - url: https://github.com/OpenLiberty/docs.git
    branches: antora
    start_path: ref/javadocs
  - url: https://github.com/OpenLiberty/docs.git
    branches: antora
    start_path: ref/commands
asciidoc:
  attributes:
    url-coderay: http://coderay.rubychan.de/
    url-coderay-gem: https://rubygems.org/gems/coderay
    icons: font
    source-highlighter: coderay
    coderay-linenums-mode: inline
    coderay-linenums: true
    coderay-css: class
    allow-uri-read: true
ui:
  bundle:
    url: src/main/content/ui/build/ui-bundle.zip
    snapshot: true    
  default_layout: general-reference


    